#!/usr/bin/env bash

cd /Users/dyc/Documents/code/go-project/src

echo "format the whole directory"
go fmt algorithm-go/...

echo "run all unit tests in this directory"
go test algorithm-go/adt/...
go test algorithm-go/problem/...
go test algorithm-go/recursive/...
go test algorithm-go/sort/...


